"""retirando o unique do endereco

Revision ID: 05d01e9dd53f
Revises: 43e3fe07b6e3
Create Date: 2026-07-24 16:23:10.600978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05d01e9dd53f'
down_revision = '43e3fe07b6e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unidade', schema=None) as batch_op:
        batch_op.alter_column('cep',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unidade', schema=None) as batch_op:
        batch_op.alter_column('cep',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
