"""atualizando model de pontos e os inserindo nos dados do usuario

Revision ID: 090599533ef4
Revises: 3b69eeb0db82
Create Date: 2026-08-03 10:39:33.255011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '090599533ef4'
down_revision = '3b69eeb0db82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pontos', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'usuarios', ['pontos'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pontos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
