"""arrumando model de pontos

Revision ID: 11bf0362178f
Revises: 99f63dc55744
Create Date: 2026-08-03 11:12:56.840031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11bf0362178f'
down_revision = '99f63dc55744'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pontos", schema=None) as batch_op:
        batch_op.alter_column("pontos_total",existing_type=sa.Integer(),nullable=False)
        

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass

    # ### end Alembic commands ###
