"""adicionando a coluna desconto

Revision ID: 3b69eeb0db82
Revises: fe5b9addaa15
Create Date: 2026-08-03 09:41:57.090196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b69eeb0db82'
down_revision = 'fe5b9addaa15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('desconto', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.drop_column('desconto')

    # ### end Alembic commands ###
