"""agora é obrigatório o cep

Revision ID: 43e3fe07b6e3
Revises: f3b35d94b2db
Create Date: 2026-07-24 15:55:12.620338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43e3fe07b6e3'
down_revision = 'f3b35d94b2db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unidade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cep', sa.String(), nullable=True))
        batch_op.create_unique_constraint(None, ['endereco'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unidade', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('cep')

    # ### end Alembic commands ###
