"""adicionado is_active para a unidade

Revision ID: 45f38dc418bc
Revises: 4f128d400945
Create Date: 2026-08-03 16:26:14.324170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45f38dc418bc'
down_revision = '4f128d400945'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unidade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unidade', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
