"""Initial

Revision ID: 45faef635845
Revises: 
Create Date: 2026-07-23 14:58:53.825383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45faef635845'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unidade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('localidade', sa.String(length=150), nullable=False),
    sa.Column('estado', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('telefone', sa.String(length=15), nullable=False),
    sa.Column('cep', sa.String(length=10), nullable=True),
    sa.Column('senha_hash', sa.String(length=225), nullable=True),
    sa.Column('perfil', sa.Enum('CLIENTE', 'COZINHEIRO', 'ATENDENTE', 'GERENCIA', 'ADMINISTRADOR', name='perfil'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email')
    )
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuarios_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuarios_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('funcionarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('unidade_id', sa.Integer(), nullable=False),
    sa.Column('cargo', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidade.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('funcionarios')
    op.drop_table('clientes')
    op.drop_table('usuarios')
    op.drop_table('unidade')
    # ### end Alembic commands ###
