"""inserindo colunas de pedido

Revision ID: 462ee1dbddee
Revises: fbddfab9df30
Create Date: 2026-07-27 19:15:02.725730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '462ee1dbddee'
down_revision = 'fbddfab9df30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('unidade_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('AGUARDANDO_PAGAMENTO', 'AGUARDANDO_CONFIRMAÇAO', 'EM_PREPARO', 'AGUARDANDO_ENTREGADOR', 'PRONTO', 'FINALIZADO', 'CANCELADO', name='status'), nullable=False),
    sa.Column('data_pedido', sa.String(length=100), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidade.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itempedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_pedido', sa.Integer(), nullable=False),
    sa.Column('estoque_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['estoque_id'], ['estoque.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_pedido'], ['pedido.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('itempedido')
    op.drop_table('pedido')
    # ### end Alembic commands ###
