"""alterando tabela funcionario

Revision ID: 4cb60dee7ec1
Revises: 45f38dc418bc
Create Date: 2026-08-03 18:18:43.233567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cb60dee7ec1'
down_revision = '45f38dc418bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('funcionarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ferias', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('funcionarios', schema=None) as batch_op:
        batch_op.drop_column('ferias')

    # ### end Alembic commands ###
