"""atualizando

Revision ID: 4db800c7b4ca
Revises: b97bacd9c919
Create Date: 2026-08-01 19:20:15.968888

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4db800c7b4ca'
down_revision = 'b97bacd9c919'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.drop_column('local_pedido')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('local_pedido', postgresql.ENUM('TOTEM', 'WEBSITE', 'BALCAO', name='localpedido'), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
