"""Cria tabela de consentimentos

Revision ID: 4e8eec7855e9
Revises: b21579077b42
Create Date: 2026-08-10 21:11:04.688329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e8eec7855e9'
down_revision = 'b21579077b42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consentimentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('finalidade', sa.Enum('PROGRAMA_FIDELIDADE', name='fidelideconsentimento'), nullable=False),
    sa.Column('aceito', sa.Boolean(), nullable=False),
    sa.Column('versao_termo', sa.String(length=20), nullable=False),
    sa.Column('data_consentimento', sa.DateTime(), nullable=True),
    sa.Column('data_revogacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'finalidade', name='uq_usuario_finalidade_consentimento')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('consentimentos')
    # ### end Alembic commands ###
