"""alterando novamente a model de pontos

Revision ID: 4f128d400945
Revises: 951fda9f0e36
Create Date: 2026-08-03 11:25:58.148594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f128d400945'
down_revision = '951fda9f0e36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pontos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('quantidade', sa.Integer(), nullable=False))
        batch_op.drop_column('pontos_total')
        batch_op.drop_column('pontos_utilizado')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pontos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pontos_utilizado', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('pontos_total', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('quantidade')
        batch_op.drop_column('tipo')

    # ### end Alembic commands ###
