"""inserindo a tabela de pagamento

Revision ID: 5ea3a6ec2566
Revises: 93eda5b0569b
Create Date: 2026-07-28 23:18:52.919678

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '5ea3a6ec2566'
down_revision = '93eda5b0569b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pagamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('metodo', postgresql.ENUM('DINHEIRO', 'DEBITO', 'CREDITO', 'PIX', 'VALE', name='metodopagamento', create_type=False), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('aprovado', sa.Boolean(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedido.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pagamento')
    # ### end Alembic commands ###
