"""inserindo valor_desconto

Revision ID: 60ef0ef0ec11
Revises: c55242535807
Create Date: 2026-08-03 10:47:43.571737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60ef0ef0ec11'
down_revision = 'c55242535807'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pontos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valor_desconto', sa.Numeric(precision=10, scale=2), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pontos', schema=None) as batch_op:
        batch_op.drop_column('valor_desconto')

    # ### end Alembic commands ###
