"""adicionando o cep novamente

Revision ID: 665b946dc739
Revises: a6f1d8028474
Create Date: 2026-07-22 15:29:29.046069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '665b946dc739'
down_revision = 'a6f1d8028474'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cep', sa.String(length=10), nullable=True))
        batch_op.alter_column('telefone',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=15),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.create_unique_constraint(None, ['cpf'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('telefone',
               existing_type=sa.String(length=15),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('cep')

    # ### end Alembic commands ###
