"""initial_3

Revision ID: 76d9e3f1cb6d
Revises: 
Create Date: 2026-07-28 16:42:58.443072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76d9e3f1cb6d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.Column('categoria', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unidade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endereco', sa.String(length=150), nullable=False),
    sa.Column('bairro', sa.String(length=150), nullable=False),
    sa.Column('cep', sa.String(length=9), nullable=False),
    sa.Column('cidade', sa.String(length=50), nullable=False),
    sa.Column('estado', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('telefone', sa.String(length=15), nullable=False),
    sa.Column('cep', sa.String(length=10), nullable=True),
    sa.Column('senha_hash', sa.String(length=225), nullable=True),
    sa.Column('perfil', sa.Enum('CLIENTE', 'COZINHEIRO', 'ATENDENTE', 'GERENCIA', 'ADMINISTRADOR', name='perfil'), nullable=False),
    sa.Column('pontos', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email')
    )
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuarios_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuarios_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estoque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_produto', sa.Integer(), nullable=False),
    sa.Column('id_unidade', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(length=150), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_produto'], ['produtos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_unidade'], ['unidade.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('funcionarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('unidade_id', sa.Integer(), nullable=False),
    sa.Column('cargo', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidade.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_table('pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('unidade_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('AGUARDANDO_PAGAMENTO', 'AGUARDANDO_CONFIRMAÇAO', 'EM_PREPARO', 'AGUARDANDO_ENTREGADOR', 'PRONTO', 'FINALIZADO', 'CANCELADO', name='status'), nullable=False),
    sa.Column('data_pedido', sa.DateTime(), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('metodo_pagamento', sa.Enum('DINHEIRO', 'DEBITO', 'CREDITO', 'PIX', 'VALE', name='metodopagamento'), nullable=False),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidade.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itempedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_pedido', sa.Integer(), nullable=False),
    sa.Column('estoque_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['estoque_id'], ['estoque.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_pedido'], ['pedido.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('itempedido')
    op.drop_table('pedido')
    op.drop_table('funcionarios')
    op.drop_table('estoque')
    op.drop_table('clientes')
    op.drop_table('usuarios')
    op.drop_table('unidade')
    op.drop_table('produtos')
    # ### end Alembic commands ###
