"""Cpf agora é uma string que comporta 11 numeros

Revision ID: 8b773ae994b0
Revises: c8141a3e6244
Create Date: 2026-07-22 15:14:31.754498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b773ae994b0'
down_revision = 'c8141a3e6244'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('cpf',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('cpf',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
