"""retirando metodo de pagamento do pedido

Revision ID: 93eda5b0569b
Revises: 76d9e3f1cb6d
Create Date: 2026-07-28 21:58:56.305685

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '93eda5b0569b'
down_revision = '76d9e3f1cb6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.drop_column('metodo_pagamento')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metodo_pagamento', postgresql.ENUM('DINHEIRO', 'DEBITO', 'CREDITO', 'PIX', 'VALE', name='metodopagamento'), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
