"""Inicial

Revision ID: 9497cbebba35
Revises: 
Create Date: 2026-07-21 09:53:37.795736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9497cbebba35'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unidade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('localidade', sa.String(length=150), nullable=False),
    sa.Column('estado', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('senha_hash', sa.String(length=225), nullable=True),
    sa.Column('perfil', sa.Enum('CLIENTE', 'FUNCIONARIO', 'GERENCIA', name='perfil'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('funcionarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('unidade_id', sa.Integer(), nullable=False),
    sa.Column('cargo', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidade.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('funcionarios')
    op.drop_table('usuarios')
    op.drop_table('unidade')
    # ### end Alembic commands ###
