"""atualizando tudo

Revision ID: 951fda9f0e36
Revises: 11bf0362178f
Create Date: 2026-08-03 11:23:54.627787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '951fda9f0e36'
down_revision = '11bf0362178f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pontos', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('pontos_pontos_total_fkey'), type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pontos', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('pontos_pontos_total_fkey'), 'usuarios', ['pontos_total'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
