"""atualizando mais coisa

Revision ID: 99f63dc55744
Revises: b827e2ab9e65
Create Date: 2026-08-03 11:02:25.048939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99f63dc55744'
down_revision = 'b827e2ab9e65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pontos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pontos_total', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('pontos_utilizado', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('data_movimentacao', sa.DateTime(), nullable=False))
        batch_op.drop_constraint(batch_op.f('pontos_pontos_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuarios', ['pontos_total'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('pontos')
        batch_op.drop_column('valor_desconto')

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valor_desconto', sa.Numeric(precision=10, scale=2), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('valor_desconto')

    with op.batch_alter_table('pontos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valor_desconto', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('pontos', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('pontos_pontos_fkey'), 'usuarios', ['pontos'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('data_movimentacao')
        batch_op.drop_column('pontos_utilizado')
        batch_op.drop_column('pontos_total')

    # ### end Alembic commands ###
