"""editando tabela de pontos

Revision ID: a4c5ecf1bce6
Revises: cbff391a557f
Create Date: 2026-08-01 18:59:17.397440

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a4c5ecf1bce6'
down_revision = 'cbff391a557f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pontos', schema=None) as batch_op:
        batch_op.drop_column('utilizado')
        batch_op.drop_column('data')

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('pontos')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pontos', sa.INTEGER(), autoincrement=False, nullable=True))

    with op.batch_alter_table('pontos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('utilizado', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
