"""Adicionado o cep

Revision ID: a6f1d8028474
Revises: 8b773ae994b0
Create Date: 2026-07-22 15:25:51.526145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6f1d8028474'
down_revision = '8b773ae994b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('cpf',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=11),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('cpf',
               existing_type=sa.String(length=11),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
