"""salvando alterações

Revision ID: abee13c2aa6d
Revises: 5ea3a6ec2566
Create Date: 2026-07-29 17:22:51.064905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abee13c2aa6d'
down_revision = '5ea3a6ec2566'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entrega', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.drop_column('entrega')

    # ### end Alembic commands ###
