"""Atualizando tabela

Revision ID: adf1a2810374
Revises: 4e8eec7855e9
Create Date: 2026-08-10 21:15:45.716575

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'adf1a2810374'
down_revision = '4e8eec7855e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consentimentos', schema=None) as batch_op:
        batch_op.alter_column('finalidade',
               existing_type=postgresql.ENUM('PROGRAMA_FIDELIDADE', name='fidelideconsentimento'),
               type_=sa.Enum('PROGRAMA_FIDELIDADE', name='fidelidadeconsentimento'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consentimentos', schema=None) as batch_op:
        batch_op.alter_column('finalidade',
               existing_type=sa.Enum('PROGRAMA_FIDELIDADE', name='fidelidadeconsentimento'),
               type_=postgresql.ENUM('PROGRAMA_FIDELIDADE', name='fidelideconsentimento'),
               existing_nullable=False)

    # ### end Alembic commands ###
