"""inserindo as tabelas de estoque e produtos

Revision ID: b2cd0c14fc6d
Revises: 05d01e9dd53f
Create Date: 2026-07-26 21:15:39.658888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2cd0c14fc6d'
down_revision = '05d01e9dd53f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.alter_column('usuarios_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('clientes_usuarios_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuarios', ['usuarios_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('funcionarios', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('funcionarios_unidade_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('funcionarios_usuario_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'unidade', ['unidade_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('unidade', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('unidade_endereco_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unidade', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('unidade_endereco_key'), ['endereco'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('funcionarios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('funcionarios_usuario_id_fkey'), 'usuarios', ['usuario_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('funcionarios_unidade_id_fkey'), 'unidade', ['unidade_id'], ['id'])

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('clientes_usuarios_id_fkey'), 'usuarios', ['usuarios_id'], ['id'])
        batch_op.alter_column('usuarios_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
