"""criando tabela para histórico de precos

Revision ID: b49a41fd7f85
Revises: a2d0e490c366
Create Date: 2026-08-02 15:41:03.405138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b49a41fd7f85'
down_revision = 'a2d0e490c366'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historico_preco',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('preco_anterior', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('preco_novo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('data_alteracao', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historico_preco')
    # ### end Alembic commands ###
