"""atulizando

Revision ID: b827e2ab9e65
Revises: 60ef0ef0ec11
Create Date: 2026-08-03 10:50:33.172773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b827e2ab9e65'
down_revision = '60ef0ef0ec11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cadastro_ativo', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('cadastro_ativo')

    # ### end Alembic commands ###
