"""inserindo localPedido

Revision ID: b97bacd9c919
Revises: a4c5ecf1bce6
Create Date: 2026-08-01 19:12:16.535949

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql



# revision identifiers, used by Alembic.
revision = 'b97bacd9c919'
down_revision = 'a4c5ecf1bce6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass

    # ### end Alembic commands ###
