"""inserindo telefone e cpf

Revision ID: c8141a3e6244
Revises: 9497cbebba35
Create Date: 2026-07-22 14:47:33.681419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8141a3e6244'
down_revision = '9497cbebba35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cpf', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('telefone', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('telefone')
        batch_op.drop_column('cpf')

    # ### end Alembic commands ###
