"""inserindo localPedido

Revision ID: ca58a82d8923
Revises: a4c5ecf1bce6
Create Date: 2026-08-01 19:08:07.969574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca58a82d8923'
down_revision = 'a4c5ecf1bce6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('local_pedido', sa.Enum('TOTEM', 'WEBSITE', 'BALCAO', name='localpedido'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.drop_column('local_pedido')

    # ### end Alembic commands ###
