"""inserindo localPedido

Revision ID: ca58a82d8923
Revises: a4c5ecf1bce6
Create Date: 2026-08-01 19:08:07.969574

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ca58a82d8923'
down_revision = 'a4c5ecf1bce6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    localpedido_enum = postgresql.ENUM(
        "TOTEM",
        "WEBSITE",
        "BALCAO",
        name="localpedido"
    )

    # Cria o tipo ENUM antes de criar a coluna
    localpedido_enum.create(
        op.get_bind(),
        checkfirst=True
    )

    # Adiciona a coluna inicialmente permitindo NULL
    with op.batch_alter_table("pedido", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "local_pedido",
                localpedido_enum,
                nullable=True
            )
        )

    # Preenche pedidos antigos
    op.execute(
        """
        UPDATE pedido
        SET local_pedido = 'BALCAO'
        WHERE local_pedido IS NULL
        """
    )

    # Torna a coluna obrigatória
    with op.batch_alter_table("pedido", schema=None) as batch_op:
        batch_op.alter_column(
            "local_pedido",
            existing_type=localpedido_enum,
            nullable=False
        )


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    localpedido_enum = postgresql.ENUM(
        "TOTEM",
        "WEBSITE",
        "BALCAO",
        name="localpedido"
    )

    with op.batch_alter_table("pedido", schema=None) as batch_op:
        batch_op.drop_column("local_pedido")

    localpedido_enum.drop(
        op.get_bind(),
        checkfirst=True
    )
    # ### end Alembic commands ###
