"""recriando o banco todo

Revision ID: cc4793f5680b
Revises: 
Create Date: 2026-08-04 19:36:59.023460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc4793f5680b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.Column('categoria', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unidade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endereco', sa.String(length=150), nullable=False),
    sa.Column('bairro', sa.String(length=150), nullable=False),
    sa.Column('cep', sa.String(length=9), nullable=False),
    sa.Column('cidade', sa.String(length=50), nullable=False),
    sa.Column('estado', sa.String(length=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('telefone', sa.String(length=15), nullable=False),
    sa.Column('cep', sa.String(length=10), nullable=True),
    sa.Column('senha_hash', sa.String(length=225), nullable=True),
    sa.Column('perfil', sa.Enum('CLIENTE', 'COZINHEIRO', 'ATENDENTE', 'GERENCIA', 'ADMINISTRADOR', 'GESTAO', name='perfil'), nullable=False),
    sa.Column('pontos_disponivel', sa.Integer(), nullable=False),
    sa.Column('valor_desconto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cadastro_ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email')
    )
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuarios_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuarios_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estoque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_produto', sa.Integer(), nullable=False),
    sa.Column('id_unidade', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(length=150), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_produto'], ['produtos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_unidade'], ['unidade.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('funcionarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('unidade_id', sa.Integer(), nullable=False),
    sa.Column('cargo', sa.String(length=30), nullable=False),
    sa.Column('ferias', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidade.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_table('historico_preco',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('preco_anterior', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('preco_novo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('data_alteracao', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('unidade_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('AGUARDANDO_PAGAMENTO', 'AGUARDANDO_CONFIRMACAO', 'EM_PREPARO', 'AGUARDANDO_ENTREGADOR', 'PAGAMENTO_RECUSADO', 'PRONTO', 'FINALIZADO', 'CANCELADO', name='status'), nullable=False),
    sa.Column('data_pedido', sa.DateTime(), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('entrega', sa.Boolean(), nullable=False),
    sa.Column('local_pedido', sa.Enum('TOTEM', 'WEB', 'BALCAO', 'PICKUP', 'APP', name='localpedido'), nullable=False),
    sa.Column('usar_pontos', sa.Boolean(), nullable=False),
    sa.Column('desconto', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidade.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('promocoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('unidade_id', sa.Integer(), nullable=True),
    sa.Column('tipo_desconto', sa.Enum('PERCENTUAL', 'VALOR_FIXO', name='tipodesconto'), nullable=False),
    sa.Column('valor_desconto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantidade_minima', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.DateTime(), nullable=False),
    sa.Column('data_fim', sa.DateTime(), nullable=False),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidade.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itempedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_pedido', sa.Integer(), nullable=False),
    sa.Column('estoque_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['estoque_id'], ['estoque.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_pedido'], ['pedido.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('metodo', sa.Enum('DINHEIRO', 'DEBITO', 'CREDITO', 'PIX', 'VALE', name='metodopagamento'), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('aprovado', sa.Boolean(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedido.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pontos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('data_movimentacao', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedido.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pontos')
    op.drop_table('pagamento')
    op.drop_table('itempedido')
    op.drop_table('promocoes')
    op.drop_table('pedido')
    op.drop_table('historico_preco')
    op.drop_table('funcionarios')
    op.drop_table('estoque')
    op.drop_table('clientes')
    op.drop_table('usuarios')
    op.drop_table('unidade')
    op.drop_table('produtos')
    # ### end Alembic commands ###
