"""adicionando a tabela de descontos

Revision ID: eddb2c2f7e1d
Revises: b49a41fd7f85
Create Date: 2026-08-02 20:14:11.608987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eddb2c2f7e1d'
down_revision = 'b49a41fd7f85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promocoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('unidade_id', sa.Integer(), nullable=True),
    sa.Column('tipo_desconto', sa.Enum('PERCENTUAL', 'VALOR_FIXO', name='tipodesconto'), nullable=False),
    sa.Column('valor_desconto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantidade_minima', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.DateTime(), nullable=False),
    sa.Column('data_fim', sa.DateTime(), nullable=False),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidade.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('promocoes')
    # ### end Alembic commands ###
