"""alterando a tabela unidade

Revision ID: f3b35d94b2db
Revises: 45faef635845
Create Date: 2026-07-24 15:29:57.630456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3b35d94b2db'
down_revision = '45faef635845'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unidade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('endereco', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('bairro', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('cidade', sa.String(length=50), nullable=False))
        batch_op.drop_column('localidade')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unidade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('localidade', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
        batch_op.drop_column('cidade')
        batch_op.drop_column('bairro')
        batch_op.drop_column('endereco')

    # ### end Alembic commands ###
