"""inserindo as tabelas de estoque e produtos

Revision ID: fab20286aa4f
Revises: b2cd0c14fc6d
Create Date: 2026-07-26 21:17:51.108821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fab20286aa4f'
down_revision = 'b2cd0c14fc6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.Column('categoria', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estoque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_produto', sa.Integer(), nullable=False),
    sa.Column('id_unidade', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(length=150), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_produto'], ['produtos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_unidade'], ['unidade.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('estoque')
    op.drop_table('produtos')
    # ### end Alembic commands ###
