"""inserindo coluna is_active

Revision ID: fbddfab9df30
Revises: fab20286aa4f
Create Date: 2026-07-27 14:25:18.580840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbddfab9df30'
down_revision = 'fab20286aa4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estoque', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estoque', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
