"""adicionando desconto por pontos

Revision ID: fe5b9addaa15
Revises: eddb2c2f7e1d
Create Date: 2026-08-03 09:34:22.649698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe5b9addaa15'
down_revision = 'eddb2c2f7e1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usar_pontos', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.drop_column('usar_pontos')

    # ### end Alembic commands ###
