import enum

class Perfil (enum.Enum):
    CLIENTE = "CLIENTE"
    COZINHEIRO = "COZINHEIRO"
    ATENDENTE = "ATENDENTE"
    GERENCIA = "GERENCIA"
    ADMINISTRADOR = "ADMINISTRADOR"
    GESTAO = "GESTAO"