import enum

class Status(enum.Enum):
    AGUARDANDO_PAGAMENTO = "AGUARDANDO PAGAMENTO" 
    AGUARDANDO_CONFIRMACAO = "AGUARDANDO CONFIRMACAO" 
    EM_PREPARO = "EM PREPARO" 
    AGUARDANDO_ENTREGADOR = "AGUARDANDO ENTREGADOR" 
    PAGAMENTO_RECUSADO = "PAGAMENTO RECUSADO"
    PRONTO = "PRONTO" 
    FINALIZADO = "FINALIZADO" #06
    CANCELADO = "CANCELADO" #vai pedir o motivo do cancelamento