import enum

class Status(enum.Enum):
    AGUARDANDO_PAGAMENTO = "AGUARDANDO_PAGAMENTO" 
    AGUARDANDO_CONFIRMACAO = "AGUARDANDO__CONFIRMACAO" 
    EM_PREPARO = "EM_PREPARO" 
    AGUARDANDO_ENTREGADOR = "AGUARDANDO_ENTREGADOR" 
    PAGAMENTO_RECUSADO = "PAGAMENTO_RECUSADO"
    PRONTO = "PRONTO" 
    FINALIZADO = "FINALIZADO" 
    CANCELADO = "CANCELADO" 