import enum

class Status(enum.Enum):
    AGUARDANDO_PAGAMENTO = "AGUARDANDO PAGAMENTO"
    AGUARDANDO_CONFIRMAÇAO = "AGUARDANDO CONFIRMACAO"
    EM_PREPARO = "EM PREPARO"
    AGUARDANDO_ENTREGADOR = "AGUARDANDO ENTREGADOR"
    PRONTO = "PRONTO"
    FINALIZADO = "FINALIZADO"
    CANCELADO = "CANCELADO"